title: my awesome title
author: GitHub helsing
email: helsing913@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  there is some description. Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: twitter-handle
github_username:  helsing

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
